# Generated by Django 5.1.7 on 2025-03-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicaCuatro', '0002_rename_prestamo_date_prestamo_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
    ]
